# Generated by Django 2.2 on 2019-12-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('x_cordinate', models.IntegerField(default=0)),
                ('y_cordinate', models.IntegerField(default=0)),
                ('direction', models.CharField(choices=[('NORTH', 'NORTH'), ('EAST', 'EAST'), ('SOUTH', 'SOUTH'), ('WEST', 'WEST')], max_length=5)),
            ],
        ),
    ]
